name: CI with Coverage and Pylint Reports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Asegura pytest y cobertura por si no están en requirements.txt
          pip install pytest pytest-cov coverage pylint

      - name: Run pytest with coverage
        run: |
          if [ -d "tests" ]; then
            # Ejecuta pytest y genera:
            # - reporte de terminal (lo guardamos en coverage_report.txt)
            # - cobertura Cobertura XML (cobertura.xml) para integraciones
            # Ajusta --cov=<paquete> a tu paquete real (backgammon)
            pytest --maxfail=1 -q \
              --cov=backgammon \
              --cov-report=term-missing \
              --cov-report=xml:cobertura.xml \
              tests | tee coverage_report.txt
          else
            echo "No tests/ directory found." > coverage_report.txt
            echo "<coverage/>" > cobertura.xml
          fi

      - name: Run Pylint and generate report
        run: |
          # Usa archivos trackeados por git; evita fallar si no hay .py
          git ls-files '*.py' | xargs -r pylint --rcfile=.pylintrc > pylint_report.txt || true

      - name: Generate reports file
        run: |
          cat << 'EOF' > generate_reports.py
          import os
          def read_file(path):
              return open(path, "r").read() if os.path.exists(path) else f"Error: Report file not found at {path}"
          coverage_report = read_file("coverage_report.txt")
          pylint_report = read_file("pylint_report.txt")
          reports_content = f"""# Automated Reports
          ## Coverage Report
          ```text
          {coverage_report}
          ```
          ## Pylint Report
          ```text
          {pylint_report}
          ```
          """
          with open("REPORTS.md", "w") as f:
              f.write(reports_content)
          EOF
          python generate_reports.py

      - name: Create Pull Request for reports
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'docs: Update automated reports [skip ci]'
          title: 'Automated Reports Update'
          body: |
            ## Automated Reports Update
            This PR contains the latest automated reports:
            - Coverage Report
            - Pylint Report
            Generated by GitHub Actions workflow.
          branch: automated-reports-update
          delete-branch: true
          add-paths: |
            REPORTS.md

